import type { Metadata } from "next";
import { pretendard } from "@/shared/assets/fonts";
import "./globals.css";
import Sidebar from "@/widgets/sidebar/ui/Sidebar";
import { LoadingBar } from "@cher1shrxd/loading";
import { colors } from "@/shared/config/tokens";
import QueryProvider from "@/shared/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} antialiased`}>
      <body className="font-pretendard bg-background text-text flex items-start">
        <QueryProvider>
          <LoadingBar color={colors.primaryBlue} />
          <Sidebar />
          <div className="flex-1">
            <main className="w-full max-w-7xl mx-auto pb-16 md:pb-0 md:pl-18">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
