import type { Metadata } from "next";
import { pretendard } from "@/shared/assets/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} antialiased`}
    >
      <body className="font-pretendard bg-background text-text">{children}</body>
    </html>
  );
}
